version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1-sdk
    working_directory: ~/repo
    steps:
      - checkout
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet run